INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Court of the Immortals", "cool", 10000, 001-366, 366-366);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Hard Tribunal", "lame", 100000, 002-366, 300-366);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("American Born", "new", 105000, 003-366, 326-366);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Warrior's Coming", "dangerous", 1000000, 004-366, 266-366);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Crowned Oracle", "wild", 80000, 005-366, 303-366);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Equinox of Venus", "lame", 150000, 006-366, 316-366);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Tears of War", "stupid", 25000, 007-366, 266-366);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Unnatural Bluebird", "cool", 5000, 008-366, 026-366);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Serpent in the Night", "ambitious", 75000, 009-366, 362-366);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Apocalypse Dying", "weird", 95000, 010-366, 166-366);

INSERT INTO users (name, age) VALUES ("Nola", 25);
INSERT INTO users (name, age) VALUES ("Joe", 18);
INSERT INTO users (name, age) VALUES ("Imaani", 30);
INSERT INTO users (name, age) VALUES ("Sanaya", 40);
INSERT INTO users (name, age) VALUES ("Isabel", 19);
INSERT INTO users (name, age) VALUES ("Ava-Rose", 22);
INSERT INTO users (name, age) VALUES ("Gregory", 25);
INSERT INTO users (name, age) VALUES ("Samad", 32);
INSERT INTO users (name, age) VALUES ("Ariana", 19);
INSERT INTO users (name, age) VALUES ("Kiana", 21);
INSERT INTO users (name, age) VALUES ("Tegan", 28);
INSERT INTO users (name, age) VALUES ("Leon", 33);
INSERT INTO users (name, age) VALUES ("Amina", 34);
INSERT INTO users (name, age) VALUES ("Ralph", 52);
INSERT INTO users (name, age) VALUES ("Henley", 24);
INSERT INTO users (name, age) VALUES ("Anne-Marie", 26);
INSERT INTO users (name, age) VALUES ("Jordan", 35);
INSERT INTO users (name, age) VALUES ("Ira", 32);
INSERT INTO users (name, age) VALUES ("Charlene", 20);
INSERT INTO users (name, age) VALUES ("Mya", 30);

INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 19, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 5, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1050, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 16, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 6, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 13, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (9000, 13, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (750, 15, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 12, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4500, 11, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 19, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 17, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3000, 3, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 18, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 15, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (750, 14, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 13, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (2000, 12, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250, 20, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (4000, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (3050, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5000, 14, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (450, 19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10000, 1, 5);